// <auto-generated />
using System;
using Boligmappa.Reminders.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Boligmappa.Reminders.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260430124722_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Boligmappa.Reminders.Api.Domain.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("DocumentType")
                        .HasColumnType("tinyint");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpiryDate")
                        .HasDatabaseName("IX_Documents_ExpiryDate");

                    b.HasIndex("PropertyId");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("Boligmappa.Reminders.Api.Domain.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("IX_Properties_OwnerId");

                    b.ToTable("Properties", (string)null);
                });

            modelBuilder.Entity("Boligmappa.Reminders.Api.Domain.ReminderSnooze", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SnoozedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("SnoozedUntil")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "SnoozedUntil")
                        .HasDatabaseName("IX_ReminderSnoozes_DocumentId_SnoozedUntil");

                    b.ToTable("ReminderSnoozes", (string)null);
                });

            modelBuilder.Entity("Boligmappa.Reminders.Api.Domain.Document", b =>
                {
                    b.HasOne("Boligmappa.Reminders.Api.Domain.Property", "Property")
                        .WithMany("Documents")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Boligmappa.Reminders.Api.Domain.ReminderSnooze", b =>
                {
                    b.HasOne("Boligmappa.Reminders.Api.Domain.Document", "Document")
                        .WithMany("Snoozes")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Boligmappa.Reminders.Api.Domain.Document", b =>
                {
                    b.Navigation("Snoozes");
                });

            modelBuilder.Entity("Boligmappa.Reminders.Api.Domain.Property", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
